### ISSUE TITLE
Logo i partially covered

### ISSUE THREAD

**Issue by adamvm** [coders-school/site#106]
![image](https://user-images.githubusercontent.com/5563693/91931347-83220e80-ece3-11ea-860e-37507d979687.png)
![image](https://user-images.githubusercontent.com/5563693/91931370-8b7a4980-ece3-11ea-8176-747ba617d405.png)

**Comment by ziobron** [comment]
@adamvm it's not covered. It is a casual wordpress dashboard icon.

**Comment by adamvm** [comment]
ok, looks like cut off at the bottom
