### ISSUE TITLE
impossible to download intermediate certificate

### ISSUE THREAD

**Issue by pawelnowakGIT** [coders-school/site#118]
There is an error, it is impossibile to download intermediate certificate from edu platform, even if all necessary modules are passed, no download is starting after clicking on "Pobierz certyfikat". There is an "executing icon" but nothing is happening.

![problem z pobraniem certyfikatu](https://user-images.githubusercontent.com/65122804/98261826-2cf07680-1f85-11eb-8d62-f1b84f28ac86.jpg)

**Comment by ziobron** [comment]
@pawelnowakGIT can you try on a different browser? For some people, it helped.

**Comment by pawelnowakGIT** [comment]
I've tried and it helped

**Comment by ziobron** [comment]
@pawelnowakGIT Can you try to download it now from https://tutor.coders.school?

**Comment by ziobron** [comment]
@pawelnowakGIT hmm... looks like it worked for you earlier anyway ;) If not, please reopen this issue.
