### ISSUE TITLE
https://coders.school/poradnik/ - dark link colors on dark subpage background 

### ISSUE THREAD

**Issue by michalantoniuk** [coders-school/site#127]
![image](https://user-images.githubusercontent.com/67523340/110459829-bc419e00-80cd-11eb-8ab5-d70225283c80.png)
Please note that you have set dark colors on dark background for links on the coders.school/poradnik subpage, which makes the links almost invisible (I'm using Chrome browser).

**Comment by ziobron** [comment]
I finally managed to fix it. We have switched to another website engine to simplify the publication of new materials, but unfortunately, not everything looks as good as it should. Thanks for reporting it. If you can spot something else - let us know :)
