### ISSUE TITLE
resetowanie hasła

### ISSUE THREAD

**Issue by LechWilk** [coders-school/site#129]
zaraz po rejestracji nowego użytkownika nie mogę się zalogować. Po zresetowaniu hasła zgodnie z procedur, linkeim aktywacyjnym i nowym hasłem - również.

**Comment by ziobron** [comment]
🏅 2 XP granted for @LechWilk
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
🏅 2 XP granted for @LechWilk
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
@LechWilk a o którą platformę chodzi? Podejrzewam, że edu.coders.school. Spróbuj zalogować się przez tę stronę - https://edu.coders.school/wp-login.php

**Comment by ziobron** [comment]
I najlepiej podaj mi jeszcze wszystkie linki lub załącz screenshoty w jaki sposób się logujesz, bo niestety tych sposobów jest więcej niż 1.
