### ISSUE TITLE
Additional filter for lessons could be helpful: TODO

### ISSUE THREAD

**Issue by adamvm** [coders-school/site#130]
Hi,

I think one more filter 'TODO" can be helpfull to sort out only items that are not done yet:
It will speed-up access and improve XP as I expect

I refer to this section:

![image](https://user-images.githubusercontent.com/5563693/116771478-10248f80-aa4c-11eb-9eae-b0894a4b6b21.png)

**Comment by ziobron** [comment]
Unfortunately it's not under our control. This platform is from third-party supplier
