### ISSUE TITLE
Testy do zadania z linuxa

### ISSUE THREAD

**Issue by Krzysiek31415** [coders-school/site#131]
Poniższa komenda nie przechodziła mi jednego z testów, a jest zgodna z treścią zadania.
**history | tail -n12 >> data/commands.txt**
Po zmianie na poniższą przechodziła test.
**history | tail -n12 >> commands.txt**

**Comment by ziobron** [comment]
🏅 2 XP granted for @Krzysiek31415
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Hej @Krzysiek31415. W treści było, aby zapisać to w pliku commands.txt, a nie data/commands.txt, więc zachowanie jest poprawne. Nie będę tego zmieniał.
PS. To Issue lepiej gdybyś zgłosić w repo coders-school/linux, bo to bezpośrednio go dotyczy i tam można się odnosić do właściwych Pull Requestów linkując je do Issue.
