### ISSUE TITLE
Small typo, Missing 'j' on homework site 

### ISSUE THREAD

**Issue by Ptysiek** [coders-school/site#133]
`Pulpit / Algorytmy / 0x1A Zadania domowe`
https://kursy.coders.school/szkolenie.html?tid=41&lid=488

There is a missing `j` character in the first sentence from task 1 -graysclae-image-algo.
```
Zadanie 1 - grayscale-image-algo
Ulepsz program grayscale-image z poprzedniej pracy domowe`j`   <--
```

**Comment by ziobron** [comment]
🏅 2 XP granted for @Ptysiek
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Fixed, thx!
