### ISSUE TITLE
List of tasks feature

### ISSUE THREAD

**Issue by Ptysiek** [coders-school/site#134]
![image](https://user-images.githubusercontent.com/18698263/129194551-4c489499-bfa8-4d3b-9bf7-cef1e7e18b2d.png)

On `coders.school/edu/punkty/` site first tasks had links to the pages with the description of that tasks.
It was a nice thing. All tasks could have it.

List like that could also exist on `kursy.coders.school/szkolenie.html`, for example under the Pulpit button.
It would boost up the on site navigation.

![image](https://user-images.githubusercontent.com/18698263/129197738-9938515b-c851-4a58-83e0-5e9c907cf203.png)

**Comment by ziobron** [comment]
🏅 2 XP granted for @Ptysiek
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
We cannot customize kursy.coders.school in that way, but I have added a link to the page with points.
![Zrzut ekranu 2021-08-18 o 11 49 41](https://user-images.githubusercontent.com/4595135/129877477-822ea222-f3a0-49c3-9d3e-3db3af9d15f0.png)

Also, all missing links are added on coders.school/edu/punkty/
