### ISSUE TITLE
[EDU]Dead download links on /C++/Intro/

### ISSUE THREAD

**Issue by pawelkolimaga** [coders-school/site#136]
Links at **https://kursy.coders.school/szkolenie.html?tid=19** doesn't work properly

Redirect to page with 404 foult information

<img width="522" alt="Bez tytułu" src="https://user-images.githubusercontent.com/66121057/164942848-237a50c3-9fbb-42f7-bfbe-352225389df3.png">

**Comment by ziobron** [comment]
Thank you @pawelkolimaga, links are now fixed. Sorry for such delay, I haven't noticed this Issue.
