### ISSUE TITLE
Agenda video from "Wstrzykiwanie zaleznosci" section is not working 

### ISSUE THREAD

**Issue by MichalMarciniakGS** [coders-school/site#138]
As mentioned in the title,
0x00 Agenda video from "Wstrzykiwanie Zależności" - "Testowanie kodu w C++" is not working.
Tested on Chrome and Microsoft Edge with the same result:
![image](https://github.com/coders-school/site/assets/72413371/1c42d922-2a44-4527-a138-50995dd515e5)

**Comment by Penthurion** [comment]
The issue has been fixed. Thanks for submitting.
