### ISSUE TITLE
replit clang-format not working

### ISSUE THREAD

**Issue by kprzygod** [coders-school/site#139]
~/GrotesqueOutstandingValue$  clang-format -style=webkit -dump-config > .clang-format
~/GrotesqueOutstandingValue$ clang-format -style=file:.clang-format -i *.cpp *.hpp
Invalid value for -style
No such file or directory

**Comment by lukasz-ziobron-more** [comment]
You should use double dash `--` before `style` and `dump-config`

```
~/GrotesqueOutstandingValue$ clang-format --style=webkit --dump-config > .clang-format
~/GrotesqueOutstandingValue$ clang-format --style=file -i *.cpp *.hpp
```

**Comment by kprzygod** [comment]
with -- all is working, you can add update to the text below the video
