### ISSUE TITLE
Fix Hugo build action

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#19]
https://github.com/coders-school/site/actions

Right now the building fails because of missing git binary. Docker image needs to be updated to contain git.

Action config file: https://github.com/coders-school/site/blob/master/.github/workflows/main.yml

1. Pull this image: lowply/build-hugo@v0.69.0
2. Modify it - install a git binary
3. Push as a new image on your repo
4. Update .github/workflows/main.ym to point to your image

**Comment by kawapa** [comment]
Ok, second attempt to this :)
