### ISSUE TITLE
Edu: Get rid of button border

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#35]
It is blue now

<img width="146" alt="Zrzut ekranu 2020-04-29 o 14 12 26" src="https://user-images.githubusercontent.com/4595135/80594554-82baf380-8a23-11ea-9967-fa462ee2f012.png">

https://coders.school/edu/courses/intro/tutor_quiz/kim-ty-jestes/

**Comment by kawapa** [comment]
Would it not be better to keep the layout consistent and don't use border here? For example, the registration button is also orange and has no border.
I have already got rid of the blue 1px border. Moreover, uf you hover the cursor over the button it will change to dark-red (similarly as the registration button).
I you don't like it - I can put it back to light blue :)

![Screenshot2](https://user-images.githubusercontent.com/30127736/80682518-fbbd5800-8ac2-11ea-9f6e-7799f9348a81.png)

![Screenshot3](https://user-images.githubusercontent.com/30127736/80682958-b9e0e180-8ac3-11ea-9429-cb7ffc4ebee9.png)

**Comment by ziobron** [comment]
OK, I agree :)

**Comment by ziobron** [comment]
Oh, wait. Doesn't work for this specific button when you are taking the quiz

https://coders.school/edu/courses/intro/tutor_quiz/twoje-cele/

<img width="1284" alt="Zrzut ekranu 2020-04-30 o 13 04 54" src="https://user-images.githubusercontent.com/4595135/80703547-4222af00-8ae3-11ea-8ac1-9c197bb63e78.png">

**Comment by kawapa** [comment]
Fixed.
