### ISSUE TITLE
EDU: Fix login screen

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#36]
Click when unlogged: https://coders.school/edu/courses/intro/tutor_quiz/kim-ty-jestes/
- [x] blue button should be #cf802a
- [x] placeholder text should be darker
- [x] "Remember me" and so on texts should be lighter

<img width="1434" alt="Zrzut ekranu 2020-04-29 o 14 14 16" src="https://user-images.githubusercontent.com/4595135/80594706-cdd50680-8a23-11ea-85b7-0b9ceea667ae.png">

**Comment by kawapa** [comment]
How about making those black and white?

![Screenshot1](https://user-images.githubusercontent.com/30127736/80681707-81400880-8ac1-11ea-98c6-98936f891d76.png)

**Comment by ziobron** [comment]
Looks good!

**Comment by ziobron** [comment]
Well, almost. Hover button is still blue ;)

**Comment by kawapa** [comment]
Fixed. Should work fine globally.
