### ISSUE TITLE
EDU: Make quiz attempts table header background darker

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#37]
Set it to #272625

<img width="557" alt="Zrzut ekranu 2020-04-29 o 14 45 02" src="https://user-images.githubusercontent.com/4595135/80597460-25757100-8a28-11ea-8468-17bf81c20e19.png">

**Comment by kawapa** [comment]
I don't know why it is not working. Changing the bottom row is possible whereas changing the header is not. Yellow is just for example.

.quiz-attempt-answers-wrap table thead {
		background-color: yellow !important;
}

.quiz-attempt-answers-wrap table td {
	background-color: yellow;
}

![Screenshot4](https://user-images.githubusercontent.com/30127736/80713908-79e62280-8af4-11ea-8763-2d0e81ab7d56.png)

**Comment by ziobron** [comment]
There was a mistake in CSS above in textarea (2 closing braces }} )

<img width="716" alt="Zrzut ekranu 2020-05-1 o 20 47 57" src="https://user-images.githubusercontent.com/4595135/80832805-9fa32280-8bed-11ea-8b53-55131ac2772c.png">

Fixed :)
