### ISSUE TITLE
Ok mark in red

### ISSUE THREAD

**Issue by adamvm** [coders-school/site#39]
![image](https://user-images.githubusercontent.com/5563693/80857618-c005c800-8c53-11ea-8ed4-a9f30e91ef8d.png)
If everything done and is ok, I would expect green or other color but not red

**Comment by kawapa** [comment]
Done.
I have also created a new colour variable named --done as we might need it in other areas as well.

**Comment by ziobron** [comment]
@adamvm You may also verify if it looks as expected now :)

**Comment by adamvm** [comment]
looks great
