### ISSUE TITLE
Low contrast for code (or preformatted text)

### ISSUE THREAD

**Issue by adamvm** [coders-school/site#40]
Low visibility due to low contrasting font color

![image](https://user-images.githubusercontent.com/5563693/80857646-f80d0b00-8c53-11ea-88af-217e9087029e.png)

**Comment by kawapa** [comment]
How about this?

pre {
color: #e83e8c
}

![sudoapt](https://user-images.githubusercontent.com/30127736/80866578-be59f580-8c8f-11ea-8c00-8ac2fecd802b.png)

We could also replace <pre> with <code> which will be the same thing.

**Comment by ziobron** [comment]
@adamvm @kawapa What about this?

<img width="647" alt="Zrzut ekranu 2020-05-4 o 14 45 50" src="https://user-images.githubusercontent.com/4595135/80967016-f55a1380-8e15-11ea-9ef4-8d8e73af86d5.png">

**Comment by adamvm** [comment]
looks ok, neutral
