### ISSUE TITLE
Marking as done for page

### ISSUE THREAD

**Issue by adamvm** [coders-school/site#41]
There is no automatic marking as done for particular page that I read and want to go further
It happens that I read, go further and 2-3 pages left not marked
Seems that there is low risk for usability to link next page action with marking done, and e.g. change button to 'mark unread'

**Comment by ziobron** [comment]
It will require changes in the LMS engine. It may cost about 1 day and updates of the platform have a risk to revert this change. I give it a low priority because of more effort than for other tasks will be needed.

**Comment by ziobron** [comment]
Now the button "Ukończ Lekcję" also moves you to the next lesson. It that the desired behaviour?

**Comment by adamvm** [comment]
@ziobron it's 'oposite' to what I propose :) but lets check VOCs

**Comment by adamvm** [comment]
Done:

![image](https://user-images.githubusercontent.com/5563693/116771362-1fefa400-aa4b-11eb-896d-f391212ebced.png)
