### ISSUE TITLE
Fix displaying of the achievements

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#42]
https://coders.school/edu/osiagniecia/

- [x] Remove white background (images have transparent background)
- [x] Remove displaying of "In" text (display: none?)
- [x] Limit max width and/or height of images? They could be smaller

<img width="772" alt="Zrzut ekranu 2020-05-6 o 10 59 53" src="https://user-images.githubusercontent.com/4595135/81159404-3888c380-8f89-11ea-8cfb-b5dfed8263bf.png">

**Comment by kawapa** [comment]
Done although I can't make those image-backgrounds transparent. Temporarily I worked around this by background-color: var(--back).

**Comment by ziobron** [comment]
> Done although I can't make those image-backgrounds transparent. Temporarily I worked around this by background-color: var(--back).

What about `background: none`?

**Comment by ziobron** [comment]
`background: none` works. I have fixed this by the way.

**Comment by kawapa** [comment]
Ktoś tu ma braki w CSS.. :P
