### ISSUE TITLE
Fix displaying of a single achievement

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#43]
https://coders.school/edu/osiagniecia/pierwsze-koty-za-ploty/

- [x] remove white top border or whatever it is
- [x] do not display the metadata (author, date, comments)?
- [x] make sure that it does not break displaying meta data in courses

<img width="772" alt="Zrzut ekranu 2020-05-6 o 11 00 09" src="https://user-images.githubusercontent.com/4595135/81160249-1cd1ed00-8f8a-11ea-99b6-a75b184599b4.png">

**Comment by kawapa** [comment]
Done but I don't see this white strip at the top.

**Comment by ziobron** [comment]
I've created Issue #46 for translation :) Just edit those files, I will do the rest ;)

**Comment by ziobron** [comment]
I don't see the white strip now too ;)
