### ISSUE TITLE
Redundant page links on 'winners' table

### ISSUE THREAD

**Issue by adamvm** [coders-school/site#45]
![image](https://user-images.githubusercontent.com/5563693/81430910-90c5ee00-9160-11ea-8cbc-4eda94fcc18d.png)
even if all registered users are able to fit on first page, links to additional pages are generated

**Comment by ziobron** [comment]
It was not a page of the ranking but the whole dashboard page was separated into subpages by this paginator.
Issue not valid anymore. The dashboard has changed, ranking moved to https://coders.school/edu/ranking/.
