### ISSUE TITLE
Untranslated parts of Gamipress and TutorLMS

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#46]
- [x] Translate missing parts of translations/cmb2-pl_PL.po (Gamipress)
- [x] Translate missing parts of translations/tutor-pl_PL.po (Tutor LMS)
- [x] Translate translations/gamipress.pot (Gamipress)

**Comment by kawapa** [comment]
Lukasz, are you sure these are the only files storing the translations? I cannot find phrases like "Required Step", "People who earned this".

See here: https://user-images.githubusercontent.com/30127736/81465632-9c023380-91cb-11ea-8935-87241e2a4514.PNG.

**Comment by ziobron** [comment]
I haven't seen any other file but I will take a look today later.
Also I an not sure if modifications in msgid are allowed. They are probably used as identifiers. I will check if it breaks something or not.

**Comment by ziobron** [comment]
@kawapa You are right. The translation was not in po file, but in pot. I have uploaded it into translations/gamipress.pot. This is the right file.

**Comment by ziobron** [comment]
Translation of the whole file is not necessary. It can be only partially translated. The most common occurrences are the most important.
