### ISSUE TITLE
Beautify buttons of prize purchase

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#47]
Make whiteish/greyish buttons look like the rest of the buttons. Change background, color, font, padding.

![Zrzut ekranu 2020-05-9 o 16 19 52](https://user-images.githubusercontent.com/4595135/81476214-f40f5900-9210-11ea-97d8-7bc1df73d7c0.png)

**Comment by Kasperice** [comment]
I propose to change:
```
button.gamipress-achievement-unlock-with-points-button {
    color: #FFFFFF;
    background: #CF802A;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
}
```

Then button will look like below:
![Zrzut ekranu z 2020-05-16 11-27-32](https://user-images.githubusercontent.com/26752357/82116300-09343c80-9769-11ea-815c-a28bfa0f90b8.png)

**Comment by ziobron** [comment]
Done as @Kasperice suggested.
