### ISSUE TITLE
Typo in setup_ubuntu.md

### ISSUE THREAD

**Issue by KrzysztofJ85** [coders-school/site#48]
Typo in https://github.com/coders-school/kurs_cpp_podstawowy/blob/master/PreWork/setup_ubuntu.md
is
std::cout << "\nHello wordl! " << name << "\n";
should be
std::cout << "\nHello world! " << name << "\n";
:)

**Comment by ziobron** [comment]
Fixed. BTW You should raise this issue in https://github.com/coders-school/kurs_cpp_podstawowy ;)

**Comment by ziobron** [comment]
Let me reopen and close this issue a few times. I am testing Github integration. Some points for this issue should appear in your account soon ;)

**Comment by ziobron** [comment]
Good, now worked. +2 XP for new Issue is on your account :) GJ!

**Comment by KrzysztofJ85** [comment]
True.
I think then, that link on that page "
https://coders.school/edu/courses/intro/lesson/zglaszanie-bledow-issues-na-githubie/
"
should be to https://github.com/coders-school/kurs_cpp_podstawowy
not https://github.com/coders-school/site/issues

KJ

niedz., 10 maj 2020 o 22:51 Łukasz Ziobroń <notifications@github.com>
napisał(a):
