### ISSUE TITLE
Converting xp points into coins

### ISSUE THREAD

**Issue by Ptysiek** [coders-school/site#52]
I'm guessing that points for achievements and module completion are not converted into coins.
Tried to refresh the page, it didn't help.

![image](https://user-images.githubusercontent.com/18698263/81918054-ad3dac80-95de-11ea-84b5-0a3005adc45e.png)

![image](https://user-images.githubusercontent.com/18698263/81918398-102f4380-95df-11ea-8951-6c82f0f4c604.png)

**Comment by ziobron** [comment]
Maybe it was a temporary glitch of the gamification plugin. I have checked just checked your account and I can see that you have 32 Monety and 32 XP. Can you confirm?

<img width="702" alt="Zrzut ekranu 2020-05-14 o 12 49 56" src="https://user-images.githubusercontent.com/4595135/81925978-8fbe1200-95e1-11ea-82d2-8ba169d0a6e9.png">

**Comment by ziobron** [comment]
@Ptysiek Can you confirm or deny that it is ok now?

**Comment by Ptysiek** [comment]
Confirm, its ok now  : D
