### ISSUE TITLE
Błąd w Linkach do osiągnięć (następny/poprzedni)

### ISSUE THREAD

**Issue by kari0036** [coders-school/site#53]
Napisy pojawiają się zbyt blisko siebie

**Comment by ziobron** [comment]
Just a comment - try to always write messages on GitHub in English. It is just an open-source good practice. Also in this case attaching a screenshot here would be useful ;)

**Comment by ziobron** [comment]
Fixed. @kari0036 can you confirm that it looks good?

**Comment by kari0036** [comment]
Fixed
