### ISSUE TITLE
Wrong redirection in kurs_cpp_podstawowy/module1/presentation_arrays.md

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#56]
There is a wrong hyperlink in "kurs_cpp_podstawowy/module1/presentation_arrays.md". In part "Zadanie" link redirects us to "https://github.com/coders-school/kurs_cpp_podstawowy/blob/master/module1/task2.cpp" instead of "https://github.com/coders-school/kurs_cpp_podstawowy/blob/master/module1/task4.cpp"

```
## Zadanie

Zmodyfikuj program, tak aby wypełniał tablicę kolejnymi nieparzystymi liczbami: 1, 3, 5, 7, ... [Pobierz zadanie](task2.cpp)
```

**Comment by ziobron** [comment]
Fixed. @Kasperice can you confirm it is ok now?

**Comment by Kasperice** [comment]
It is ok now, thanks
