### ISSUE TITLE
Module 1 - Podstawy C++ - conditionals subject - Typo in code

### ISSUE THREAD

**Issue by niemarcin** [coders-school/site#57]
https://coders.school/edu/courses/podstawy-c-typy-auto-funkcje-instrukcje-warunkowe-petle-tablice/lesson/instrukcje-warunkowe-lekcja/#zadanie

In code given in "Zadanie" section of the lesson there is:

` retrun 0; ` there is typo - should be ` return `

**Comment by ziobron** [comment]
Fixed. BTW this issue is about the content of kurs_cpp_podstawowy, so it should be raised there ;)
