### ISSUE TITLE
Incorrect answer in quiz about function `fun(1, "text");`

### ISSUE THREAD

**Issue by lisie-sprawy** [coders-school/site#58]
Right answer is incorrect (I hope so:D) anyway, if I think wrong, all answers are incorrect
![obraz](https://user-images.githubusercontent.com/65089187/81981981-5ca36f00-9631-11ea-9764-694bc9f55c41.png)

**Comment by ziobron** [comment]
Already answered on Discord :) You must pick all correct answers :)

**Comment by lisie-sprawy** [comment]
Yes, of course, thx! So one positive is here - I learned how to report a issue:)
