### ISSUE TITLE
Wrong size borders on page "Nagrody"

### ISSUE THREAD

**Issue by kari0036** [coders-school/site#59]
Borders should be similar

**Comment by kari0036** [comment]
.edumax-blog-listing .blog-details-img {
    max-width: 96px;
    margin: auto;
    height: 145px;                
    align-items: center;        
    justify-content: center;   
    display: flex;                   
}

**Comment by kawapa** [comment]
@kari0036 
Could you please attach the screenshot showing how it looks like on your machine? The borders are just fine on mine (Chrome & Firefox).
