### ISSUE TITLE
Wrong color button

### ISSUE THREAD

**Issue by kari0036** [coders-school/site#60]
If you pass a lesson "Podstawy C++: typy, auto, funkcje, instrukcje warunkowe, pętle, tablice",
Button "UKOŃCZ KURS" is white.

**Comment by kari0036** [comment]
.tutor-lead-info-btn-group .tutor-course-compelte-form-wrap button {
    display: block;
    width: 100%;
    background: #cf802a; 
    color: var(--tutor-light-color);


.tutor-lead-info-btn-group .tutor-course-compelte-form-wrap button:hover {
    background: var(--tutor-primary-hover-color); 
    color: #fff;
}

**Comment by kawapa** [comment]
Done! Thanks @kari0036 !
