### ISSUE TITLE
Wrong commend to install clang++ - Intro course

### ISSUE THREAD

**Issue by anraf1001** [coders-school/site#61]
There is a mistake in the intro course in section about installing compilers. To install `clang++` on Linux you need to use `sudo apt install clang` not `clang++`
![Opera Zrzut ekranu_2020-05-17_095329_coders school](https://user-images.githubusercontent.com/28186871/82138958-cd5ead00-9824-11ea-88d6-4bfe38dd620e.png)

**Comment by ziobron** [comment]
Thanks. Fixed now.
