### ISSUE TITLE
Invalid links in cpp_basics.pdf

### ISSUE THREAD

**Issue by KrzysztofJ85** [coders-school/site#62]
https://coders.school/edu/courses/podstawy-c-typy-auto-funkcje-instrukcje-warunkowe-petle-tablice/
pdf link:
https://github.com/coders-school/kurs_cpp_podstawowy/raw/master/module1/cpp_basics.pdf
inside pdf there are links to tasks (e.g. page 38) and they link to: http://localhost:8000/module1/task3.cpp

**Comment by kawapa** [comment]
I am sorry it took so long. It is now fixed and awaiting @ziobron approval.

https://github.com/coders-school/kurs_cpp_podstawowy/pull/289
