### ISSUE TITLE
double headers / missing coders school image

### ISSUE THREAD

**Issue by KrzysztofJ85** [coders-school/site#63]
https://coders.school/edu/courses/podstawy-c-typy-auto-funkcje-instrukcje-warunkowe-petle-tablice/lesson/funkcje-lekcja/
https://github.com/coders-school/kurs_cpp_podstawowy/blob/master/module1/presentation_functions.md
and
https://coders.school/edu/courses/podstawy-c-typy-auto-funkcje-instrukcje-warunkowe-petle-tablice/lesson/petle-lekcja/
https://github.com/coders-school/kurs_cpp_podstawowy/blob/master/module1/presentation_loops.md

Double headers at the beginning or coders school link looking like some image is missing

**Comment by kawapa** [comment]
@ziobron 
Please correct me if I'm wrong but lessons on the education platform are not linked to the markdown files at GH/kurs_cpp_podstawowy/module1. Those are used to generate cpp_basics.pdf.

**Comment by kawapa** [comment]
Both images and links are turned off at the Education platform due to relative links. I'll rename the headers to avoid confusion.
Unfortunately can't just remove those as they are useful when generating a PDF from multiple MD files.
