### ISSUE TITLE
Quiz validation not working properly

### ISSUE THREAD

**Issue by KrzysztofJ85** [coders-school/site#65]
![quiz](https://user-images.githubusercontent.com/50273916/82644352-78021180-9c11-11ea-9e5c-21a459a98b8e.jpg)

**Comment by ziobron** [comment]
Thanks. I have disabled "randomize" option, which should shuffle answers. Let me know if the issue occurs anymore. If no, I think we will close this issue.

**Comment by kawapa** [comment]
#ziobron
Something must have went wrong because the questions are still shuffled :) I have disabled it for you (just STL section/lesson) and now everything seems ok. @KrzysztofJ85 please confirm.

**Comment by KrzysztofJ85** [comment]
I confirm. Everything now seems to be ok.

**Comment by kawapa** [comment]
Ok. 

@ziobron
I reported this issue to the platform owners (https://github.com/themeum/tutor/issues/13). For the time being we could disable the randomness in all quizzes.

**Comment by ziobron** [comment]
Great @kawapa. Thank you :)
