### ISSUE TITLE
Points counting for code review is working incorrectly

### ISSUE THREAD

**Issue by jakjan95** [coders-school/site#66]
During the code review, system is giving 2 points for each comment, even for solution owner comment added on someone's review. I think that it should counts only 2 points for each code review not the comment.

**Comment by ziobron** [comment]
Right now it is fixed not to consider PR author's comments. It should cover most of the cases, however nothing prohibits users from publishing each comment as a separate code review. For now, we will stay with this solution. If someone will be misusing it in a future you can raise a new Issue.
