### ISSUE TITLE
No translation

### ISSUE THREAD

**Issue by adamvm** [coders-school/site#67]
![image](https://user-images.githubusercontent.com/5563693/83164921-1d831c80-a10d-11ea-843c-4d91b6905c9f.png)

**Comment by ziobron** [comment]
Interesting fact is, that this phrase is not in a translation file, but it is hardcoded in PHP. ANy incoming plugin update may overwrite this change. I will check if it is possible to move it into translation file.

**Comment by ziobron** [comment]
What do you think?

<img width="386" alt="Zrzut ekranu 2020-06-2 o 23 47 12" src="https://user-images.githubusercontent.com/4595135/83573278-6979fb00-a52b-11ea-8d24-497a1c00efe4.png">

**Comment by adamvm** [comment]
+1
