### ISSUE TITLE
Migrate poradnik

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#7]
- [x] Replace HTML with MD
- [x] Add proper front matter in YAML
- [x] Save necessary assets in poradnik directory (images, etc.)
- [x] Use youtube shortcode for embedding YT video
- [x] Use [admonitions](https://hugoloveit.com/theme-documentation-shortcodes/#admonition) for digressions 
- [ ] Create new popup in MailerLite for article rating (@ziobron) or look for special hugo plugins for ratings

**Comment by kawapa** [comment]
@ziobron 
I leave the last one to you :)

By the way: is `http://coders.school/#newsletter` a correct link to newsletter?
