### ISSUE TITLE
Page "Regulamin" is missing

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#73]
![image](https://user-images.githubusercontent.com/26752357/83566063-afc95d00-a51f-11ea-9638-55354a87a974.png)
![image](https://user-images.githubusercontent.com/26752357/83566094-bbb51f00-a51f-11ea-9a42-8623677fb3f0.png)

I think I saw somewhere something like "Regulamin", but maybe it just seemed to me

**Comment by ziobron** [comment]
Link was broken. Fixed.
