### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#78]
In "Zadanie domowe" https://coders.school/edu/courses/stl-1-kontenery-sekwencyjne/lesson/praca-domowa-5/

Some images are missing (or not displaying correctly):
![image](https://user-images.githubusercontent.com/26752357/83864781-8712b480-a725-11ea-954a-bc9742132d56.png)
![image](https://user-images.githubusercontent.com/26752357/83864805-90038600-a725-11ea-8d19-968270d568f8.png)

**Comment by kawapa** [comment]
Ok, it turned out the images are not displayed in lessons intentionally (display: none). This is to preserve the portability of repo (if we were to move it somewhere else, it would corrupt the appearance).
