### ISSUE TITLE
Migrate co-nas-wyroznia

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#8]
- [x] Replace HTML with MD
- [x] Add proper front matter in YAML
- [x] Use [font-awesome shortcodes ](https://hugoloveit.com/theme-documentation-content/#font-awesome)

https://coders.school/co-nas-wyroznia/

**Comment by kawapa** [comment]
I assume one-column layout is fine?

Problem that occurred: awesome fonts appear in TOC which looks bad. I'll try to workaround it somehow.

![Screenshot from 2020-04-17 20-17-50](https://user-images.githubusercontent.com/30127736/79601857-c93a5500-80e9-11ea-8402-b7c6d9dbdaa3.png)

**Comment by kawapa** [comment]
How about we use several "&nbsp;" so the icon, at least, does not blend with the header?

![2](https://user-images.githubusercontent.com/30127736/79603798-474c2b00-80ed-11ea-8b48-df17ea8896e3.png)

**Comment by ziobron** [comment]
I have already commented that in Code Review. Let's try to put the icon first, then the title.
