### ISSUE TITLE
"Zaliczone" in quiz result is too long for the green box

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#88]
![image](https://user-images.githubusercontent.com/26752357/84872823-a93ff700-b082-11ea-8a5d-d0794a05037c.png)

**Comment by kawapa** [comment]
Should be fine now. Please check on your browser and confirm.

![Screenshot from 2020-06-18 09-55-13](https://user-images.githubusercontent.com/30127736/84993681-e28f6a00-b149-11ea-9fae-f64ca12aec5f.png)

**Comment by Kasperice** [comment]
It is correct now, thanks
