### ISSUE TITLE
Migrate faq

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#9]
- [x] Replace HTML with MD
- [x] Add proper front matter in YAML
- [x] Try this accordion template (html)

<details>
  <summary>
    Visible text
  </summary>
  Hidden text; seen after clicking that accordion arrow
</details>

- [ ] If not possible check [Code Toggle](https://gohugo.io/getting-started/code-toggle/) out

**Comment by kawapa** [comment]
Done:

https://github.com/coders-school/site/pull/11/commits/13efe84b611aa44105b848eddcd8ce5f5b1c706c
