### ISSUE TITLE
"Typy danych – quiz" issue with passing with all answeres correct

### ISSUE THREAD

**Issue by pawelnowakGIT** [coders-school/site#91]
I made this test 9 times and since 2nd attempt only issue was with 1 question, about correct way of writing a floating point number, I tried many variations and it is always bad. As I figured out from lesson materials and discord, correct answer should be like on the picture, but every time it is as an error. I've tried also other combinations and it is still the same. Can you check it if it is an real error or not?

I thought that maybe, if test was passed with one error it can't be passed with more points anymore, but I've tried with other tests and it seems that this is not true.

![zapisy zmiennoprzecinkowe](https://user-images.githubusercontent.com/65122804/84933018-7ffc8680-b0d5-11ea-80cb-6a9cd14ed8ee.JPG)
![zapisy zmiennoprzecinkowe odpowiedzi](https://user-images.githubusercontent.com/65122804/84933022-83900d80-b0d5-11ea-891e-f1d38c87c4bc.JPG)
![zapisy zmiennoprzecinkowe wariacja](https://user-images.githubusercontent.com/65122804/84933028-8559d100-b0d5-11ea-9ad8-65c2e75c9f71.JPG)

**Comment by ziobron** [comment]
There is such a problem and people were having such issues earlier. There is a bug in the quiz module and unfortunately, the only thing I can do is to disable randomization of answers.
Maybe this will help. @pawelnowakGIT let me know if the issue still occurs.

**Comment by pawelnowakGIT** [comment]
Now it works properly

![zapisy zmiennoprzecinkowe poprawne odpowiedzi](https://user-images.githubusercontent.com/65122804/84999494-84ff1b80-b151-11ea-911d-f9f6206e5a7e.JPG)
