### ISSUE TITLE
[Module][Basics 1#][Quiz] The platform does not display the question correctly

### ISSUE THREAD

**Issue by MaciejSalamonski** [coders-school/site#92]
I think this question is displayed incorrectly.
![question](https://user-images.githubusercontent.com/62703601/85162164-2a54e500-b261-11ea-85dd-1ee64f278432.PNG)

**Comment by ziobron** [comment]
Thanks. Issue fixed.

![Zrzut ekranu 2020-06-22 o 06 40 49](https://user-images.githubusercontent.com/4595135/85249184-5afc7080-b453-11ea-95e4-360eba240bc4.png)
