### ISSUE TITLE
View Attempt in quiz has different theme than whole platform

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#93]
I did not notice that #89 was closed. The header table is better now, but whole "View Attempt" od "Details" of single quiz have different theme
![image](https://user-images.githubusercontent.com/26752357/86220010-44f15d00-bb83-11ea-9a0b-7b6d2e0d75b7.png)
I think it will be better to use same color theme as whole platform (for example, like below):
![image](https://user-images.githubusercontent.com/26752357/86220109-62bec200-bb83-11ea-9b28-23ffc172030c.png)

**Comment by ziobron** [comment]
Thanks. After update the way of displaying results has changed. Check now and confirm if it looks ok.

**Comment by Kasperice** [comment]
Now it looks ok, but I found something else: 
![image](https://user-images.githubusercontent.com/26752357/86222788-fba30c80-bb86-11ea-9257-fdce3f2b4c13.png)
Text on button is visible only during hover

**Comment by ziobron** [comment]
Can you provide a link to this page? I cannot find it.

**Comment by Kasperice** [comment]
https://coders.school/edu/courses/narzedzia-3/tutor_quiz/systemy-budowania-quiz/?view_quiz_attempt_id=2535

**Comment by ziobron** [comment]
I hope it looks good now

![Zrzut ekranu 2020-07-1 o 12 07 18](https://user-images.githubusercontent.com/4595135/86231839-71ad7080-bb93-11ea-99c3-efc3cc705b9a.png)

**Comment by Kasperice** [comment]
It is ok now, thanks :)
