### ISSUE TITLE
Footer can grow too big

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#95]
Now I have 4 achievments unlocked, all of them are displayed in footer, I am afraid that if I gain more of them the footer will be growing more and more, maybe it will be better to display only icons or only names of achievments?

![image](https://user-images.githubusercontent.com/26752357/86221194-de6d3e80-bb84-11ea-9eff-02e9f77b179e.png)

**Comment by ziobron** [comment]
What about now? :) Icons are clickable.
There is a limit to max 10 achievements to display here. If there are more the button "Show more" should appear.

![Zrzut ekranu 2020-07-1 o 11 40 54](https://user-images.githubusercontent.com/4595135/86229279-c51dbf80-bb8f-11ea-9b16-0e0ff42525d3.png)

**Comment by Kasperice** [comment]
It is perfect (for me) now :)
