### ISSUE TITLE
"Wszystkie moduły" navigation button style can be changed

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#97]
![image](https://user-images.githubusercontent.com/26752357/87052718-6399c880-c201-11ea-8dc9-7f6b8628932f.png)

Button to move to the next page is orange only on hover. It will be better when it will be orange (like the rest of the theme)

**Comment by Kasperice** [comment]
.edumax-pagination ul li.pagination-parent a {
    background: #cf802a;
    color: #fff;
    transition: 300ms;
    font-weight: 700;
    font-size: 14px;
}

This css will change button to orange, but it will be orange when hover also. I don't know if it will be better to change color on hover or not.

**Comment by kawapa** [comment]
Thanks for figuring it out! Done.

**Comment by Kasperice** [comment]
Thanks, looks better :)
