### ISSUE TITLE
List of topics in "Wszystkie moduły" can be shorter

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#98]
![image](https://user-images.githubusercontent.com/26752357/87052928-a6f43700-c201-11ea-9485-77ef47ee7822.png)

List is too long, and require additional scrolling. It is now much longer than one page of courses:
![image](https://user-images.githubusercontent.com/26752357/87053087-d3a84e80-c201-11ea-816c-a08c715bee5b.png)

Is it possible to add button to expand the list?

**Comment by kawapa** [comment]
I have limited the maximum height of the filter and added a scroll bar. Let me know if this suits you guys.

https://coders.school/edu/courses/

```css
.single-filter {
	max-height: 600px;
	overflow-y: auto;
}
```

**Comment by Kasperice** [comment]
For me it is ok :)
