### ISSUE TITLE
Improve style in module preview

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#99]
![image](https://user-images.githubusercontent.com/26752357/87325032-39157b80-c531-11ea-813f-a9563a4f50bf.png)

example: https://coders.school/edu/courses/testowanie-1-catch2-given-when-then/lesson/testowanie-1/

Book icon near "Lista lekcji" should be better positioned.
Arrow used to open "Lista Lekcji" on orange background (background could be bigger)

**Comment by kawapa** [comment]
Please check. Should be alright now.

**Comment by Kasperice** [comment]
It is better now, thanks
